{{- if .Values.rbac.install -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Namespace }}-{{ template "edge-core.fullname" . }}-clusterrolebinding
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: {{ .Release.Namespace }}-{{ template "edge-core.fullname" . }}-clusterrole
subjects:
  - kind: ServiceAccount
    name: {{ include "edge-core.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end -}}

