apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "edge-core.fullname" . }}
  labels:
    {{- include "edge-core.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "edge-core.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "edge-core.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "edge-core.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: HTTP_HOST
              value: "{{ .Values.pod.http.host }}"
            - name: HTTP_PORT
              value: "{{ .Values.pod.http.port }}"
            - name: GEOLOCATION_UPDATER_CRON_SPEC
              value: "{{ .Values.pod.geolocation.cron.spec }}"
            - name: IPINFO_URL
              value: "{{ .Values.pod.ipinfo.url }}"
            - name: IPINFO_ACCESS_TOKEN
              value: "{{ .Values.pod.ipinfo.token }}"
            - name: NODE_NAME
              value: spec.nodeName
          ports:
            - name: http
              containerPort: {{ .Values.pod.http.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /live
              port: http
          readinessProbe:
            httpGet:
              path: /ready
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
