apiVersion: v1
kind: Service
metadata:
  name: {{ include "edge-core.fullname" . }}
  labels:
    {{- include "edge-core.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.grpcport }}
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    {{- include "edge-core.selectorLabels" . | nindent 4 }}
